apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-petclinic-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
