apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-lb
  labels:
    app: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
